USE CompanyDB;
GO

CREATE TABLE DEPT (
    DUNM INT PRIMARY KEY,
    SSN CHAR(9),
    HIRDATE DATE,
    DN VARCHAR(100)
);

CREATE TABLE LOC (
    DUNM INT,
    LOC VARCHAR(100),
    PRIMARY KEY (DUNM, LOC),
    FOREIGN KEY (DUNM) REFERENCES DEPT(DUNM)
);

CREATE TABLE EMP (
    SSN CHAR(9) PRIMARY KEY,
    Fname VARCHAR(50),
    Lname VARCHAR(50),
    gender CHAR(1),
    super_id CHAR(9),
    BD DATE,
    DUNM INT,
    FOREIGN KEY (super_id) REFERENCES EMP(SSN),
    FOREIGN KEY (DUNM) REFERENCES DEPT(DUNM)
);

ALTER TABLE DEPT
ADD CONSTRAINT FK_DEPT_MANAGER FOREIGN KEY (SSN) REFERENCES EMP(SSN);

CREATE TABLE PROJECT (
    PNUM INT PRIMARY KEY,
    PN VARCHAR(100),
    LOC VARCHAR(100),
    CITY VARCHAR(100),
    DUNM INT,
    FOREIGN KEY (DUNM) REFERENCES DEPT(DUNM)
);

CREATE TABLE WORK (
    SSN CHAR(9),
    PNUM INT,
    hours DECIMAL(5,2),
    PRIMARY KEY (SSN, PNUM),
    FOREIGN KEY (SSN) REFERENCES EMP(SSN),
    FOREIGN KEY (PNUM) REFERENCES PROJECT(PNUM)
);

CREATE TABLE Dependent (
    dnum VARCHAR(50),
    BD DATE,
    GENDER CHAR(1),
    ssn CHAR(9),
    PRIMARY KEY (dnum, ssn),
    FOREIGN KEY (ssn) REFERENCES EMP(SSN)
);
